#!/bin/bash

if [ "$1" == "" ]; then
  echo "Usage: ops_start_cluster CIDR/MASK"
  echo "E.g.: ./ops_start_cluster 192.168.1.0/24"
  exit 1
fi

echo "Initializing cluster"

rm -rf $HOME/.kube

sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
sudo swapoff -a

sudo kubeadm reset
rm -rf /run/kubernetes
sudo kubeadm init \
  --pod-network-cidr=$1 \
  --upload-certs \
  --control-plane-endpoint=k8s-cluster

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
echo KUBECONFIG=~/.kube/config >> /bashrc
export KUBECONFIG=~/.kube/config
