#!/bin/bash
kubectl get deployment
echo "Press ENTER to describe deployments (q) to quit"
read -n 1 waiting
if [ "$waiting" == "q" -o "$waiting" == "Q" ]; then
  exit 0
fi
kubectl describe deployment
